---

- name: Control variables for categories creation
  ansible.builtin.set_fact:
    create_categories: true
  when: category_created is defined

- name: Control variables for tags creation
  ansible.builtin.set_fact:
    create_tags: true
  when: tags_created is defined

- name: Create a category
  community.vmware.vmware_category:
    category_name: "{{ category }}"
    category_description: "{{ category_description }}"
    category_cardinality: 'multiple'
    validate_certs: false
    state: present
  register: category_created
  when: create_categories is not defined

- name: Create tag
  community.vmware.vmware_tag:
    tag_name: "{{ item }}"
    category_name: "{{ category }}"
    state: present
    validate_certs: false
  loop: "{{ tags }}"
  register: tags_created
  when: create_tags is not defined

- name: Deploy Virtual Machines
  ansible.builtin.include_tasks: provision.yml

- name: Add tags to the virtual machine
  community.vmware.vmware_tag_manager:
    tag_names:
      - tag: tag_var
        category: "{{ category }}"
    object_name: "{{ item.vm_name }}"
    object_type: VirtualMachine
    state: add
    validate_certs: false
  loop_control:
    loop_var: tag_var
  loop: "{{ item.add_tags }}"
