---

- ansible.builtin.set_fact:
    create_categories: true
  when: category_created

- ansible.builtin.set_fact:
    create_tags: true
  when: tags_created
 
- name: Create a category
  community.vmware.vmware_category:
    category_name: "{{ category }}"
    category_description: "{{ category_description }}"
    category_cardinality: 'multiple'
    validate_certs: false
    state: present
  register: category_created
  when: create_categories == false

- name: Create tag
  community.vmware.vmware_tag:
    tag_name: "{{ item }}"
    category_name: "{{ category }}"
    state: present
    validate_certs: false
  loop: "{{ tags }}"
  register: tags_created
  when: create_tags

- name: Deploy Virtual Machines
  ansible.builtin.include_tasks: provision.yml

- name: Add tags to the virtual machine
  community.vmware.vmware_tag_manager:
    tag_names: "{{ item.add_tags }}"
    object_name: "{{ item.vm_name }}"
    object_type: VirtualMachine
    state: add
    validate_certs: false
