---
# Default variables for the gcp_instances role

project_id: your-gcp-project-id
credentials_file: /path/to/your-service-account.json
region: europe-southwest1
zone: europe-southwest1-a

# Number of instances to create
number_of_instances: 1

# GCE machine type
machine_type: "e2-standard-16"

# RHEL 9 image details
image_project: rhel-cloud
image_family: rhel-9

# If set to true, the role will NOT generate new SSH keys, 
# and will use 'precreated_public_key' as provided externally.
use_precreated_keys: false
precreated_public_key: ""

# Paths to store SSH keys if generating them
ssh_key_path: "~/.ssh/id_rsa.pub"

# Network details
network_name: ansiblenet
subnetwork_name: ansiblesubnet
subnet_cidr: 10.0.0.0/24

# Firewall rule name
firewall_name: ansiblerules
