---
- name: "Ensure the {{ network_name }} network exists"
  google.cloud.gcp_compute_network:
    name: "{{ network_name }}"
    project: "{{ project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ service_account_file }}"
    service_account_contents: "{{ service_account_content }}"
    # For a custom-mode network, set auto_create_subnetworks to false
    auto_create_subnetworks: true
  register: network_result

- debug: msg="{{ network_result }}"

- name: "Ensure the {{ subnetwork_name }} subnetwork exists"
  google.cloud.gcp_compute_subnetwork:
    name: "{{ subnetwork_name }}"
    project: "{{ project_id }}"
    region: "{{ region }}"
    network:
      selfLink: "https://www.googleapis.com/compute/v1/projects/{{ project_id }}/global/networks/{{ network_name }}"
    ip_cidr_range: "{{ subnet_cidr }}"
    auth_kind: serviceaccount
    service_account_file: "{{ service_account_file }}"
    service_account_contents: "{{ service_account_content }}"
  register: subnetwork_result

- name: "Allow inbound SSH (22) and HTTPS (443) from anywhere"
  google.cloud.gcp_compute_firewall:
    name: "{{ firewall_name }}"
    project: "{{ project_id }}"
    network:
      selfLink: "https://www.googleapis.com/compute/v1/projects/{{ project_id }}/global/networks/{{ network_name }}"
    auth_kind: serviceaccount
    service_account_file: "{{ service_account_file }}"
    service_account_contents: "{{ service_account_content }}"
    allowed:
      - ip_protocol: tcp
        ports:
          - "22"
          - "443"
    source_ranges:
      - "0.0.0.0/0"
  register: firewall_result

- name: "Generate SSH key pair (if not using pre-created keys)"
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_path }}"
    type: rsa
    size: 2048
    comment: "Key for GCP RHEL instances"
  register: generated_keys
  when: not use_precreated_keys
  run_once: true

- name: "Create {{ number_of_instances }} instance(s)"
  google.cloud.gcp_compute_instance:
    name: "rhel9-instance-{{ item }}"
    project: "{{ project_id }}"
    zone: "{{ zone }}"
    auth_kind: serviceaccount
    service_account_file: "{{ service_account_file }}"
    service_account_contents: "{{ service_account_content }}"
    machine_type: "{{ machine_type }}"
    disks:
      - auto_delete: true
        boot: true
        type: pd-standard
        initialize_params:
          source_image: "projects/{{ image_project }}/global/images/family/{{ image_family }}"
    network_interfaces:
      - network: 
          selfLink: "https://www.googleapis.com/compute/v1/projects/{{ project_id }}/regions/{{ region }}/subnetworks/{{ subnetwork_name }}"
        subnetwork: "{{ subnetwork_name }}"
        access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
    metadata:
      ssh-keys: |
        rhel: {{ account_key_decoded.stdout }}
  loop: "{{ range(1, number_of_instances | int + 1) | list }}"
  when: use_precreated_keys is true
